export const LOADED_HOME_INFO = 'LOADED_HOME_INFO';
export const LOAD_HOME_INFO = 'LOAD_HOME_INFO';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
